// src/components/DashboardPage.jsx
import React, { useState, useEffect } from 'react';
import { API_BASE_URL } from '../utils/api'; // Import API base URL

const DashboardPage = () => {
  const [username, setUsername] = useState('User'); // Default username

  useEffect(() => {
    const token = localStorage.getItem('token');
    const user = JSON.parse(localStorage.getItem('user') || '{}');

    if (!token) {
      window.location.href = '/login'; // Redirect to login if no token
      return;
    }

    // Verify token with backend
    fetch(`${API_BASE_URL}/api/verify`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`
      }
    })
    .then(response => response.json())
    .then(data => {
      if (!data.valid) {
        localStorage.removeItem('token');
        localStorage.removeItem('user');
        window.location.href = '/login'; // Redirect if token invalid
      } else {
        setUsername(user.username || 'User'); // Set username from localStorage
      }
    })
    .catch(() => {
      localStorage.removeItem('token');
      localStorage.removeItem('user');
      window.location.href = '/login'; // Redirect on network error during verification
    });
  }, []); // Empty dependency array means this runs once on mount

  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    window.location.href = '/login'; // Redirect to login after logout
  };

  const handleAIWorkoutPlansClick = () => {
    window.location.href = '/ai-workout-plans';
  };

  // Helper component for feature cards
  const FeatureCard = ({ icon, title, description, onClick }) => (
    <div className="feature-card" onClick={onClick} style={{ cursor: onClick ? 'pointer' : 'default' }}>
      <div className="icon">{icon}</div>
      <h3>{title}</h3>
      <p>{description}</p>
    </div>
  );

  return (
    <div>
      <nav className="navbar">
        <div className="logo">IntelliFit</div>
        <div className="user-info">
          <span className="welcome">Welcome, <span id="username">{username}</span>!</span>
          <button className="logout-btn" onClick={handleLogout}>Logout</button>
        </div>
      </nav>

      <div className="dashboard-container">
        <div className="welcome-section">
          <h1>Welcome to Your Fitness Journey! 🚀</h1>
          <p>Your AI-powered fitness companion is ready to help you achieve your goals. Get personalized workout plans, track your progress, and unlock your potential with IntelliFit.</p>
        </div>

        <div className="features-grid">
          <FeatureCard
            icon="🤖"
            title="AI Workout Plans"
            description="Get personalized workout routines generated by our advanced AI, tailored specifically to your fitness level and goals."
            onClick={handleAIWorkoutPlansClick}
          />
          <FeatureCard
            icon="📊"
            title="Progress Tracking"
            description="Monitor your fitness journey with detailed analytics, progress charts, and achievement milestones."
          />
          <FeatureCard
            icon="🎯"
            title="Goal Setting"
            description="Set and track your fitness goals with our intelligent goal-setting system that adapts to your progress."
          />
          <FeatureCard
            icon="💪"
            title="Exercise Library"
            description="Access a comprehensive library of exercises with detailed instructions and form guidance."
          />
          <FeatureCard
            icon="🏆"
            title="Achievements"
            description="Earn badges and rewards as you hit your milestones and stay motivated on your fitness journey."
          />
          <FeatureCard
            icon="👥"
            title="Community"
            description="Connect with other fitness enthusiasts, share your progress, and get inspired by the community."
          />
        </div>
      </div>
    </div>
  );
};

export default DashboardPage;